name: Apt Pin Versions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  update-versions:
    name: Update Apt Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: master
          path: repo
      - name: Checkout dockerfile-pin repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: pszenher/dockerfile-pin
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: master
          path: dockerfile-pin
      - name: Install Python requirements.txt
        run: pip install -r dockerfile-pin/requirements.txt
      - name: Run Dependency Parser Kinetic
        run: python3 dockerfile-pin/dockerfile_pin.py repo/docker/jackal-kinetic.Dockerfile -w -d --no-cache
      - name: Run Dependency Parser Melodic
        run: python3 dockerfile-pin/dockerfile_pin.py repo/docker/jackal-melodic.Dockerfile -w -d --no-cache
      - name: Run Dependency Parser Noetic
        run: python3 dockerfile-pin/dockerfile_pin.py repo/docker/jackal-noetic.Dockerfile -w -d --no-cache
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.9.1
        with:
          title: Update Pinned Apt Versions
          body: Update Dockerfile apt version pins to latest version available
          commit-message: update jackal-kinetic.Dockerfile pinned apt versions
          branch: update-apt
          path: repo
